#!/bin/sh

# Run format
echo "Running format..."
output=$(bunx @biomejs/biome format . ./src --write)
exit_code=$?

# Check if the format failed
if [ $exit_code -ne 0 ]; then
  echo "format failed:"
  echo "$output"
  exit 1 # Return Error Code
fi

# Output succeeded
echo "$output"

exit 0
